name: CI

on:
  push:
      branches: [main]
  pull_request:
      branches: [main]

jobs:
  build:
    strategy:
      matrix:
        include:
          - xcode: "26.0"
            deployment_target: ""
    runs-on:  macos-26
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: ./other/download_libs.sh $DOWNLOAD_LIBS_ARGS
        env:
          DOWNLOAD_LIBS_ARGS: ${{ github.event_name == 'pull_request' && '--skip-plugins' || '' }}

      - name: Build
        run: xcodebuild -project iina.xcodeproj ONLY_ACTIVE_ARCH=NO CODE_SIGNING_ALLOWED=NO -scheme iina -configuration Release -derivedDataPath "$RUNNER_TEMP/rawya-derived" ${{ matrix.deployment_target }}
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

      - name: Archive
        run: tar cvJf "$RUNNER_TEMP/rawya.tar.xz" -C "$RUNNER_TEMP/rawya-derived/Build/Products/Release" Rawya.app

      - name: Save artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Rawya
          path: ${{ runner.temp }}/rawya.tar.xz
